services:
  # React Frontend Service
  react-frontend:
    image: react-frontend:1.0
    build:
      context: ../../Frontend/coderabhishek
      dockerfile: DockerFile
    container_name: react-frontend
    ports:
      - "3000:80" # Serve on port 3000
    networks:
      - app-network
    depends_on:
      - eureka-server
      - gateway
      - auth-service
      - blog-service
    environment:
      - REACT_APP_API_URL=http://gateway:8080 # Set your API endpoint here
      
  # Eureka Server
  eureka-server:
    image: eureka:1.0
    build:
      context: .
      dockerfile: eureka/DockerFile
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - app-network
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
      - EUREKA_SERVER_PORT=8761
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Gateway Service
  gateway:
    image: gateway:1.0
    build:
      context: .
      dockerfile: gateway/DockerFile
    container_name: gateway-service
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - JAVA_OPTS=-Xms256m -Xmx512m

  # Auth Service
  auth-service:
    image: auth:1.0
    build:
      context: .
      dockerfile: auth/DockerFile
    container_name: auth-service
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - JAVA_OPTS=-Xms256m -Xmx512m

 # Blog Service
  blog-service:
    image: blog:1.0
    build:
      context: .
      dockerfile: blog/DockerFile
    container_name: blog-service
    ports:
      - "8082:8082"
    networks:
      - app-network
    depends_on:
      - eureka-server
      - mongo
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - MONGO_URI=mongodb://mongo:27017/blog
      - JAVA_OPTS=-Xms256m -Xmx512m
      
     # MongoDB Container
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27018:27017"
    networks:
      - app-network
    volumes:
      - mongo_data:/data/db


networks:
  app-network:
    driver: bridge
    
volumes:
  mongo_data:  # This is the missing volume definition

