server:
  port: 8081
  
spring:
  data:
    mongodb:
      url: ${MONGO_URI}
  application:
    name: AUTH
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
      
  instance:
    hostname: eureka
    prefer-ip-address: true
    