server:
  port: 8081
  
spring:
  data:
    mongodb:
      url: localhost:27017/blog
  application:
    name: AUTH
      
eureka:
  client:
    serviceUrl:
      globalUrl: http://localhost:8761/eureka
      
  instance:
    hostname: localhost
    prefer-ip-address: true
    